spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    ## 整合sentinel，配置sentinel控制台的地址
    sentinel:
      transport:
        ## 指定控制台的地址，默认端口8080
        dashboard: localhost:8080
      #配置限流之后，响应内容
      scg:
        fallback:
          ## 两种模式，一种是response返回文字提示信息，
          ## 一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
          mode: response
          ## 响应的状态
          response-status: 200
          ## 响应体
          response-body: '{"code": 50020,"message": "接口繁忙，请稍后重试！"}'

    gateway:
      routes:
        - id: dxoj-backend-user-service
          uri: lb://dxoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: dxoj-backend-question-service
          uri: lb://dxoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: dxoj-backend-judge-service
          uri: lb://dxoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: dxoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2